apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
spec:
  containers:
  - name: crashing-container
    image: busybox
    command: ['sh', '-c', 'exit 1']  # Always exits with error
  restartPolicy: OnFailure
