apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: memory-hog
    image: busybox
    command: ['sh', '-c', 'tail -f /dev/null']
    resources:
      requests:
        memory: "1Gi"
      limits:
        memory: "100Mi"  # Too low, may cause OOM
