---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns

---
apiVersion: example.com/v1
kind: Website
metadata:
  name: my-blog
  namespace: default
spec:
  domain: blog.example.com
  replicas: 2
  port: 8080

---
apiVersion: example.com/v1
kind: Website
metadata:
  name: my-shop
  namespace: test-ns
spec:
  domain: shop.example.com
  replicas: 1
  port: 9090
